name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: "true"
          path: "PrixumLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/PrixumLauncher-source PrixumLauncher-${{ env.VERSION }}
          mv PrixumLauncher-Linux-Qt6-Portable*/PrixumLauncher-portable.tar.gz PrixumLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PrixumLauncher-Linux-aarch64-Qt6-Portable*/PrixumLauncher-portable.tar.gz PrixumLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PrixumLauncher-*.AppImage/PrixumLauncher-*-x86_64.AppImage PrixumLauncher-Linux-x86_64.AppImage
          mv PrixumLauncher-*.AppImage.zsync/PrixumLauncher-*-x86_64.AppImage.zsync PrixumLauncher-Linux-x86_64.AppImage.zsync
          mv PrixumLauncher-*.AppImage/PrixumLauncher-*-aarch64.AppImage PrixumLauncher-Linux-aarch64.AppImage
          mv PrixumLauncher-*.AppImage.zsync/PrixumLauncher-*-aarch64.AppImage.zsync PrixumLauncher-Linux-aarch64.AppImage.zsync
          mv PrixumLauncher-macOS*/PrixumLauncher.zip PrixumLauncher-macOS-${{ env.VERSION }}.zip
          mv PrixumLauncher-macOS*/PrixumLauncher.dmg PrixumLauncher-macOS-${{ env.VERSION }}.dmg
          mv PrixumLauncher-macOS-Portable*/PrixumLauncher-portable.zip PrixumLauncher-macOS-Portable-${{ env.VERSION }}.zip

          tar --exclude='.git' -czf PrixumLauncher-${{ env.VERSION }}.tar.gz PrixumLauncher-${{ env.VERSION }}

          for d in PrixumLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PrixumLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PrixumLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in PrixumLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PrixumLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PrixumLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Prixum Launcher ${{ env.VERSION }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            PrixumLauncher-Linux-x86_64.AppImage
            PrixumLauncher-Linux-x86_64.AppImage.zsync
            PrixumLauncher-Linux-aarch64.AppImage
            PrixumLauncher-Linux-aarch64.AppImage.zsync
            PrixumLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PrixumLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PrixumLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            PrixumLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            PrixumLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            PrixumLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            PrixumLauncher-macOS-${{ env.VERSION }}.zip
            PrixumLauncher-macOS-${{ env.VERSION }}.dmg
            PrixumLauncher-macOS-Portable-${{ env.VERSION }}.zip
            PrixumLauncher-${{ env.VERSION }}.tar.gz
